setwd("D:/RStudio")
getwd()
data_full <- read.csv("household_power_consumption.txt", sep = ";", na.strings="?")
head(data_full)
names(data_full)
nrow(data_full)
data1 <- subset(data_full, Date %in% c("1/2/2007","2/2/2007"))
data1$Date <- as.Date(data1$Date, format="%d/%m/%Y")
with(data1,plot(Global_active_power~ Date, type = "1"))
datetime <- paste(as.Date(data1$Date), data1$Time)
data1$Datetime <- as.POSIXct(datetime)

png("plot2.png", width=480, height=480)
plot(data1$Global_active_power~ data1$Datetime, type = "l",ylab = "Global Access Power (Kilowatts)", xlab = "")
dev.off()
